// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 3.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'downtogame';

  static const String assets_default_ground_png = 'assets/default/ground.png';
  static const String downtogame$assets_default_ground_png = 'packages/downtogame/assets/default/ground.png';

  static const String assets_default_player_png = 'assets/default/player.png';
  static const String downtogame$assets_default_player_png = 'packages/downtogame/assets/default/player.png';

  static const String assets_default_wall_png = 'assets/default/wall.png';
  static const String downtogame$assets_default_wall_png = 'packages/downtogame/assets/default/wall.png';
}
